##encoding=utf-8

from archives.database import client, birth, death, marriage, divorce
from archives.emailbot import efa_client
from datetime import datetime
import time

def stringlize(number):
    res = list()
    while 1:
        number, m = divmod(number, 1000)
        res.append(str(m).zfill(3))
        if number < 1000:
            res.append(str(number))
            break
    return ",".join(res[::-1])

def run_monitor():
    """send records counter information to Admin and Amina every day.
    """
    while 1:
        message_lines = list()
        message_lines.append("This is a message automatically generated by Sanhe's email Bot.")
        for collection in [birth, death, marriage, divorce]:
            message_lines.append("\tIn %s collection we have %s records." % (
                    collection.name, stringlize(collection.count())))
        message_lines.append("By %s." % datetime.now())
        message = "\n".join(message_lines)
        efa_client.send_text(["sanhe.hu@theeagleforce.net", "Amina.Khawaja@theeagleforce.net"], 
                             "Archive Crawler Daily Report", 
                             message)
        print("Email been sent at %s, ZZZ..." % datetime.now())
        time.sleep(3600*24)
        
if __name__ == "__main__":
    run_monitor()